name: Build & publish docker image

on:
  push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            dotwee/traefik-adguard-sync
            ghcr.io/dotwee/traefik-adguard-sync
          flavor: |
            latest=true
          tags: |
            type=raw,value=latest
            type=sha
          labels: |
            maintainer=Lukas Wolfsteiner <lukas@wolfsteiner.media>
            org.opencontainers.image.title=traefik-adguard-sync
            org.opencontainers.image.source="https://github.com/${{ github.repository }}"

      - name: Build and push docker image with version tag
        uses: docker/build-push-action@v5
        id: docker-build
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update Docker Hub repository description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          repository: dotwee/traefik-adguard-sync
